{% set version = '0.3.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-dupree
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dupree_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dupree/dupree_{{ version }}.tar.gz
  sha256: e098c9bf603b4ccef208a077852cf8a890f906b08865e96006a27ae8c3070c61

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-lintr >=2.0.0
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-stringdist >=0.9.5.5
    - r-tibble
  run:
    - r-base
    - r-dplyr
    - r-lintr >=2.0.0
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-stringdist >=0.9.5.5
    - r-tibble

test:
  commands:
    - $R -e "library('dupree')"           # [not win]
    - "\"%R%\" -e \"library('dupree')\""  # [win]

about:
  home: https://github.com/russHyde/dupree
  license: MIT
  summary: Identifies code blocks that have a high level of similarity within a set of R files.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: dupree
# Type: Package
# Title: Identify Duplicated R Code in a Project
# Version: 0.3.0
# Author: Russ Hyde, University of Glasgow
# Maintainer: Russ Hyde <russ.hyde.data@gmail.com>
# Description: Identifies code blocks that have a high level of similarity within a set of R files.
# URL: https://github.com/russHyde/dupree
# BugReports: https://github.com/russHyde/dupree/issues
# License: MIT + file LICENSE
# Encoding: UTF-8
# Language: en-GB
# LazyData: true
# Suggests: testthat (>= 2.1.0), knitr, rmarkdown
# Imports: dplyr, purrr, tibble, magrittr, methods, stringdist (>= 0.9.5.5), lintr (>= 2.0.0), rlang
# RoxygenNote: 7.1.0
# Collate: 'utils.R' 'dupree.R' 'dupree_classes.R' 'dupree_data_validity.R' 'dupree_code_enumeration.R' 'dups-class.R'
# NeedsCompilation: no
# Packaged: 2020-03-30 17:27:58 UTC; russ
# Repository: CRAN
# Date/Publication: 2020-04-21 10:20:02 UTC
